import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import configparser

import pandas as pd

from common.utilities import getDBRecord


class MailUtility:
    def __init__(self):
        self.smtp_host = "smtp.office365.com"
        self.smtp_port = 587
        self.sender_email = "Notificationemail"
        self.sender_password = "Configure"  # Use environment variables in a real-world scenario
        self.config_file = "../config.ini"  # Path to the property file

    def read_property(self, key):
        """Read properties from a configuration file."""
        config = configparser.ConfigParser()
        config.read(self.config_file)
        return config.get("EMAIL", key)

    def send_email(self, subject, message_body, attachment_path=None):
        try:
            # Read recipient(s) from the configuration file
            recipients = self.read_property("to").split(",")

            # Set up the email
            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = ", ".join(recipients)
            msg['Subject'] = subject

            # Add the email body
            msg.attach(MIMEText(message_body, 'html'))

            # Attach the file
            if attachment_path:
                attachment = MIMEBase('application', 'octet-stream')
                with open(attachment_path, 'rb') as file:
                    attachment.set_payload(file.read())
                encoders.encode_base64(attachment)
                attachment.add_header(
                    'Content-Disposition',
                    f'attachment; filename={attachment_path.split("/")[-1]}'
                )
                msg.attach(attachment)

            # Connect to the SMTP server
            server = smtplib.SMTP(self.smtp_host, self.smtp_port)
            server.starttls()  # Secure the connection
            server.login(self.sender_email, self.sender_password)

            # Send the email
            server.sendmail(self.sender_email, recipients, msg.as_string())
            print("Sent message successfully!")

            # Close the connection
            server.quit()

        except Exception as e:
            print(f"Failed to send email: {e}")


def generate_email_template(manager_name, test_cases, link, user_story_details):
    """
    Generate an email template with placeholders dynamically filled.

    :param manager_name: Name of the manager
    :param test_cases: List of dictionaries with test case details
    :param link: URL to the detailed test cases
    :return: Formatted email body as a string
    """
    # Email Header
    tech_mapping = {
        "bva": "Boundary Value Analysis",
        "ecp": "Equivalent Class Partitioning",
        "dtt": "Decision Table Testing",
        "st": "State Transitioning",
        "uc": "Use Case Testing"
    }
    htmltable=test_cases.to_html(index=False, escape=False)
    html_rows = htmltable.split("<tr>")
    html_rows[1:] = [f'<tr style="background-color: {"lightblue" if i % 2 == 0 else "white"};">{row[4:]}' for i, row in
                     enumerate(html_rows[1:])]

    email_body = f"""
      <html>
      <head>
          <style>
              table {{
                  width: 100%;
                  border-collapse: collapse;
              }}
              th {{
                  background-color: #002060;
                  color: white;
                  padding: 8px;
                  text-align: left;
              }}
              td {{
                  padding: 8px;
                  border: 1px solid #ddd;
              }}
              tr:nth-child(even) {{
                  background-color: #C0E6F5;
              }}
              tr:nth-child(odd) {{
                  background-color: white;
              }}
          </style>
      </head>
      <body>
       <p>Dear {manager_name},</p>
        <p>This is an automated email to notify you that the test cases for the assigned user story have been successfully generated by the AI Agent. Below is the traceability chart, providing an overview of the alignment of test cases with the requirements:</p>
        <p>{user_story_details}</p>
        <h3>Traceability Chart:</h3>
          <table>
        {''.join(html_rows)}
        </table>
          <p>You can view and download the detailed test cases through the following link:</p>
        <p><a href="{link}">{link}</a></p>
        <p>Please review the test cases and make changes if required</p>
        <p>Thank you for your time.</p>
        <p>Best regards,<br>SakVerse</p>
      </body>
      </html>
      """



# email_body = f"""
#     <p>Dear {manager_name},</p>
#     <p>This is an automated email to notify you that the test cases for the assigned user story have been successfully generated by the AI Agent. Below is the traceability chart, providing an overview of the alignment of test cases with the requirements:</p>
#
#     <h3>Traceability Chart:</h3>
#
#     """
#     # Add test cases to the email body
#     # <table border="1" style="border-collapse: collapse; width: 100%;">
#     #     <thead>
#     #         <tr style="background-color: #f2f2f2;">
#     #             <th colspan="3">{user_story_details}</th>
#     #         </tr>
#     #         <tr style="background-color: #f2f2f2;">
#     #             <th>Requirement Detail</th>
#     #             <th>Test Summary</th>
#     #             <th>Test Technique Used</th>
#     #         </tr>
#     #     </thead>
#     #     <tbody>
#     # for case in test_cases:
#     #     email_body += f"""
#     #     <tr>
#     #         <td>{case['requirment_summary']}</td>
#     #         <td>{case['summary']}</td>
#     #         <td>{tech_mapping.get(case['technique'])}</td>
#     #     </tr>
#     #     """
#     test_cases.to_html(index=False, escape=False)
#     # Closing the table and email
#     email_body += f"""
#
#     <p>You can view and download the detailed test cases through the following link:</p>
#     <p><a href="{link}">{link}</a></p>
#     <p>Please review the test cases and make changes if required</p>
#     <p>Thank you for your time.</p>
#     <p>Best regards,<br>SakVerse</p>
#     """
    return email_body

def generate_email_template_error(manager_name, test_cases, link, user_story_details):
    """
    Generate an email template with placeholders dynamically filled.

    :param manager_name: Name of the manager
    :param test_cases: List of dictionaries with test case details
    :param link: URL to the detailed test cases
    :return: Formatted email body as a string
    """
    # Email Header
    tech_mapping = {
        "bva": "Boundary Value Analysis",
        "ecp": "Equivalent Class Partitioning",
        "dtt": "Decision Table Testing",
        "st": "State Transitioning",
        "uc": "Use Case Testing"
    }
    html_rows = test_cases.split("<tr>")
    html_rows[1:] = [f'<tr style="background-color: {"lightblue" if i % 2 == 0 else "white"};">{row[4:]}' for i, row in
                     enumerate(html_rows[1:])]

    email_body = f"""
      <html>
      <head>
          <style>
              table {{
                  width: 100%;
                  border-collapse: collapse;
              }}
              th {{
                  background-color: #002060;
                  color: white;
                  padding: 8px;
                  text-align: left;
              }}
              td {{
                  padding: 8px;
                  border: 1px solid #ddd;
              }}
              tr:nth-child(even) {{
                  background-color: #C0E6F5;
              }}
              tr:nth-child(odd) {{
                  background-color: white;
              }}
          </style>
      </head>
      <body>
       <p>Dear {manager_name},</p> <p>This is an automated email to notify you that the test cases for the assigned 
       user story have been Interupted due to some server error or network issues. we are looking into it to get the 
       service back.</p> <p>{user_story_details}</p>
        <p>Thank you for your time. and Patience. We will notify you as soon as service is up</p>
        <p>Best regards,<br>SakVerse</p>
      </body>
      </html>
      """



# email_body = f"""
#     <p>Dear {manager_name},</p>
#     <p>This is an automated email to notify you that the test cases for the assigned user story have been successfully generated by the AI Agent. Below is the traceability chart, providing an overview of the alignment of test cases with the requirements:</p>
#
#     <h3>Traceability Chart:</h3>
#
#     """
#     # Add test cases to the email body
#     # <table border="1" style="border-collapse: collapse; width: 100%;">
#     #     <thead>
#     #         <tr style="background-color: #f2f2f2;">
#     #             <th colspan="3">{user_story_details}</th>
#     #         </tr>
#     #         <tr style="background-color: #f2f2f2;">
#     #             <th>Requirement Detail</th>
#     #             <th>Test Summary</th>
#     #             <th>Test Technique Used</th>
#     #         </tr>
#     #     </thead>
#     #     <tbody>
#     # for case in test_cases:
#     #     email_body += f"""
#     #     <tr>
#     #         <td>{case['requirment_summary']}</td>
#     #         <td>{case['summary']}</td>
#     #         <td>{tech_mapping.get(case['technique'])}</td>
#     #     </tr>
#     #     """
#     test_cases.to_html(index=False, escape=False)
#     # Closing the table and email
#     email_body += f"""
#
#     <p>You can view and download the detailed test cases through the following link:</p>
#     <p><a href="{link}">{link}</a></p>
#     <p>Please review the test cases and make changes if required</p>
#     <p>Thank you for your time.</p>
#     <p>Best regards,<br>SakVerse</p>
#     """
    return email_body


# Example Usage
if __name__ == "__main__":
    mail_utility = MailUtility()
    subject = "Your Test Cases Generation has been Completed"
    user_story_detail = f"""SELECT reference_key,detail FROM tcg.userstory where _id=180"""
    storydetail = getDBRecord(user_story_detail, False)
    test_cases = f"""SELECT 
                        r.detail AS "Requirment Summry",
                        COUNT(CASE WHEN technique = 'Boundary Value Analysis' THEN 1 END) AS "Boundary Value Analysis",
                        COUNT(CASE WHEN technique = 'Equivalent Class Partitioning' THEN 1 END) AS "Equivalent Class Partitioning",
                        COUNT(CASE WHEN technique = 'Decision Table Testing' THEN 1 END) AS "Decision Table Testing",
                        COUNT(CASE WHEN technique = 'State Transitioning' THEN 1 END) AS "State Transitioning",
                        COUNT(CASE WHEN technique = 'Use Case Testing' THEN 1 END) AS "Use Case Testing"
                    FROM 
                        `tcg`.`test_cases` t 
                    JOIN 
                        tcg.requirments r ON t.requirment_id = r.id
                    where 
                    t.project_id=2 and t.userstory_id=180
                    GROUP BY 
                        requirment_id
                    ORDER BY 
                        requirment_id;"""
    # Query the MySQL database for matching records
    test_cases_list = getDBRecord(test_cases, True)
    # tech_mapping = {
    #     "Boundary Value Analysis": "bva",
    #     "Equivalent Class Partitioning": "ecp",
    #     "Decision Table Testing": "dtt",
    #     "State Transitioning": "st",
    #     "Use Case Testing": "uc"
    # }
    # if not test_cases_list:
    #     test_cases_list = None
    # finaltest_cases_list = []
    # if test_cases_list is not None:
    #     for row in test_cases_list:
    #         tempdata = {
    #             "id": row['id'],
    #             "requirment_id": row['requirment_id'],
    #             "requirment_summary": row['requirment_detail'],
    #             "technique": tech_mapping.get(row['technique']),
    #             "summary": row['summary'],
    #             "test_steps": json.loads(row['test_steps'].decode('utf-8')),
    #             "expected_result": row['expected_result'],
    #             "test_data": json.loads(row['test_data'].decode('utf-8')),
    #         }
    #         finaltest_cases_list.append(tempdata)

    df = pd.DataFrame(test_cases_list)
    body = generate_email_template("User", df, "http://tcg.saksoft.com:5175/ManualProject/2", "KAN-84")

    attachment = "C:/UNITE_SUITE/TCG/Project_repo/info.txt"
    mail_utility.send_email(subject, body,attachment)
